sudo: required
services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-292808
  - gcloud config set compute/zone us-central1-c	
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t mkawtharani/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mkawtharani/react-test npm test

after_success:
  - docker build -t mkawtharani/multi-client ./client
  - docker build -t mkawtharani/multi-nginx ./nginx
  - docker build -t mkawtharani/multi-server ./server
  - docker build -t mkawtharani/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mkawtharani/multi-client
  - docker push mkawtharani/multi-nginx
  - docker push mkawtharani/multi-server
  - docker push mkawtharani/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-041427875799
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
